
Neos:
  Imagine:
    driver: Imagick
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        dbname: neos
        user: neos
        password: N30sPass!
        host: 'localhost'
